### ISSUE TITLE
Liza's Journey (Liza Floyd)

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/todo-app-react#20]
Once upon a time, there was a girl with an obsessive relationship with Project 3.  She spent all of lab day nagging her instructors about oAuth and Figaro and security and Rails.  She did not, however, do lab.

She would like to thank her instructors for their impossible levels of patience, and submit as proof that she really does want to learn React the following tutorial that she did last night.
\https://github.com/lizafloyd/tictactutorial

She plans to look at lab in the coming days, and will resubmit then.

As to her Project 3 journey, she finally understands why Jesse said "Don't do oAuth."

The End.

**Comment by amaseda** [comment]
:+1: Please let me know if you have any questions/comments as you continue to dive into React.
