### ISSUE TITLE
Latoya's Todo Lab (still in progress)

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/todo-app-react#24]
I did not pull from the todo repo. I wanted to start fresh without extra code i didn't understand.
unfortunately, it was still difficult for me. Not feeling too hot about this lab at all.  I needed a lot of help from tutorial across the web.
complete: 2/2
comfort: 2/2

https://lwatsonlm.github.io/todo-app/

**Comment by jshawl** [comment]
👍 Let me know if you wanna pair on this one - I'd be happy to!
